### ISSUE TITLE
Wrong link in README

### ISSUE THREAD

**Issue by ifraixedes** [rust10x/rust-web-app#6]
I've found out in the README, that the link attached to "Topic video - Code clean -  `#[cfg_attr(...)]` for unit test" is the same as the one attached to "Topic video - The Reasoning Behind Differentiating ModelControllers and ModelManager".

It seems that's the correct one assigned to "Topic video - The Reasoning Behind Differentiating ModelControllers and ModelManager".

**Comment by jeremychone** [comment]
ho cool, thanks for reporting. Will fix that asap.

**Comment by jeremychone** [comment]
I fixed it in 8c19f5c35a1c604605f1dacd01d3f9bb2b559ab1

Thanks for reporting.
