### ISSUE TITLE
Question Regarding JWT Token Salt

### ISSUE THREAD

**Issue by euwei7** [rust10x/rust-web-app#7]
Hi there, I watched your Rust-related videos on YouTube and found them really impressive and helpful. After going through your JWT code, I have a question: Why do you generate a unique UUID as the salt for each user's JWT token and store it in the PostgreSQL user table? Every time there's validation, the token salt needs to be fetched from the PostgreSQL user table. I'm curious why you didn't opt to store the token salt in an in-memory database like Redis instead of PostgreSQL. Wouldn't it be more efficient to store it in Redis?🌹👍

**Comment by jeremychone** [comment]
First, using a unique token salt per user is a cost-effective added security measure that enhances the token hashing scheme.

The fact that it is unique per user, in addition to a system-wide salt, means that even if the system salt is compromised somehow, one would need access to the database to obtain the individual user's salt.

Second, the design strategy involves using the main database as the source of truth for core data, and password and token salts are considered core user data. Without them, the user cannot access the product.

If or when performance becomes an issue, the token salt could be stored in a shared cache (e.g., Redis/ValKey) or even at the web-server instance as an edge cache, as it is very small in nature and its growth is relatively constrained.

Feel free to go to the Rust10x discord if you have any questions: discord rust10x: https://discord.gg/XuKWrNGKpC

**Comment by jeremychone** [comment]
By the way, the web tokens are not JWT tokens, as the JWT specification tends to try to do too much, which in turn can expose security concerns.
